language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: RyanJarv
  password:
    secure: V4xiEErpLt4psj4ac4LzNucg0fMQlHfLj3F8/zfrxhiLjIR79P11P/aCxz922GzooyRs6Y76lZJLHGRTB/AYpyrZOlJHUmgUm9W7Ki4FtiP5f5gNALUfdn0zDImJ4MjCFcf9QEUDfR4GMVkyPbdlC08HhEL4rqKkajcxqhitmhS4ucYgtQBezWZS18lHWVwJ6Odgkr644MeUngDX8xy526gkryQmhOPHvaKYdLHA5UxnRhN4aSP8g7kczmnDIn7Tv12S9ihsbx01VidP/hKltjHusvr/yNPTzNMAvlRs7eHVdbe5hMyPMDT8vJV0F/2hVQIdK7DnRD+WyIWcFzt2ayAPWvnIaHQoIZ6dJs76OsDPHSkj+ICmo+eFgB5+nUwrA3XGBywgSwpVTB0XSw4cs67DamsxnuGdPVz0akKkdue38aeMrR9jfh4DHXXrRi7VXMEmuGifXz9dsz5cnM5Lbr+V6PW0E7nwEacub++6AgplARXyGsNR3sfvm6Ik1hWQ2GdubW8zWMrlT29yZ0KqszgSvGBwv4/hgQvuJSOUplK6WFhQNZAlmOyDYgF56Zy7bjZOsZVrVuy6+D8ofR6M+ovPOXB45bOsj1TtUmh6iq3MRA6lNaJCmDNruy6uPf0UKt3Ym9d9aukppE+KL8MqAsNlxyEk6jQ+iw/2wxNvcxY=
  on:
    tags: true
    repo: RyanJarv/aws_session_recorder
    python: 3.8
